AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A serverless Patch Server for Jamf Pro using AWS.

Resources:
  PatchServerFunc:
    Type: AWS::Serverless::Function
    Properties:
      Handler: patch_server.lambda_handler
      Runtime: python3.6
      CodeUri: ./src/PatchServerFunc
      Environment:
        Variables:
          S3_BUCKET: !Ref Bucket
      Policies:
        Statement:
          - Effect: Allow
            Action: s3:ListBucket
            Resource: !Sub 'arn:aws:s3:::${Bucket}'
          - Effect: Allow
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${Bucket}/*'
      Events:
        Software:
          Type: Api
          Properties:
            Path: /jamf/v1/software
            Method: get
        SoftwareTitles:
          Type: Api
          Properties:
            Path: /jamf/v1/software/{proxy+}
            Method: get
        PatchTitle:
          Type: Api
          Properties:
            Path: /jamf/v1/patch/{proxy+}
            Method: get

  SubscriptionFunc:
    Type: AWS::Serverless::Function
    Properties:
      Handler: subscription.lambda_handler
      Runtime: python3.6
      CodeUri: ./src/SubscriptionFunc
      Timeout: 180
      Environment:
        Variables:
          S3_BUCKET: !Ref Bucket
          TABLE_NAME: !Ref SubscriptionsTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
             - dynamodb:DeleteItem
             - dynamodb:GetItem
             - dynamodb:PutItem
             - dynamodb:Scan
            Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${SubscriptionsTable}'
          - Effect: Allow
            Action:
             - s3:DeleteObject
             - s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${Bucket}/*'
      Events:
        Subscribe:
          Type: Api
          Properties:
            Path: /subscription/subscribe
            Method: post
        UnSubscribe:
          Type: Api
          Properties:
            Path: /subscription/unsubscribe/{title}
            Method: post
        SyncTimer:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)

  RestApiFunc:
    Type: AWS::Serverless::Function
    Properties:
      Handler: rest_api.lambda_handler
      Runtime: python3.6
      CodeUri: ./src/RestApiFunc
      Timeout: 10
      Environment:
        Variables:
          S3_BUCKET: !Ref Bucket
          TABLE_NAME: !Ref SubscriptionsTable
      Policies:
        Statement:
          - Effect: Allow
            Action: dynamodb:GetItem
            Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${SubscriptionsTable}'
          - Effect: Allow
            Action:
             - s3:GetObject
             - s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${Bucket}/*'
      Events:
        PostDefinition:
          Type: Api
          Properties:
            Path: /title
            Method: post
        PutDefinition:
          Type: Api
          Properties:
            Path: /title/{title}
            Method: put
        PostVersion:
          Type: Api
          Properties:
            Path: /title/{title}/version
            Method: post

  AccountsFunc:
    Type: AWS::Serverless::Function
    Properties:
      Handler: signup.lambda_handler
      Runtime: python3.6
      CodeUri: ./src/AccountsFunc
      Environment:
        Variables:
          TABLE_NAME: !Ref AccountsTable
          API_SECRET_KEY: !Ref ApiSecretKey
      Policies:
        Statement:
          - Effect: Allow
            Action:
             - dynamodb:DeleteItem
             - dynamodb:GetItem
             - dynamodb:PutItem
             - dynamodb:Scan
            Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${AccountsTable}'
          - Effect: Allow
            Action: ses:SendEmail
            Resource: '*',
            Condition:
              StringEquals:
                ses:FromAddress: 'noreply@communitypatch.com'
      Events:
        NewAccount:
          Type: Api
          Properties:
            Path: /accounts
            Method: post
        ActivateAccount:
          Type: Api
          Properties:
            Path: /accounts/activate
            Method: get

  Bucket:
    Type: AWS::S3::Bucket

  AccountsTable:
    Type: AWS::Serverless::SimpleTable
    PrimaryKey:
      Name: id
      Type: String

  SubscriptionsTable:
    Type: AWS::Serverless::SimpleTable

Parameters:
  ApiSecretKey:
    Type: String
    Description: The parameter name for the encrypted API Secret Key.
