AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: A community managed patch server for Jamf Pro.

Parameters:

  ApiTokenSecretKey:
    Type: String
    Description: The key used for generating and validating API tokens.

  DomainName:
    Type: String
    Description: The custom domain name for the API.

  EmailSenderAddress:
    Type: String
    Description: The "from" address for email notifications from this service.

  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: The ID of hosted zone for the Route53 record.

  CertificateId:
    Type: String
    Description: The UUID for the certificate to use for the custom domain.

  EncryptionKeyId:
    Type: String
    Description: ID of the KMS key to decrypt parameter store values.

  DatabaseKeyParameter:
    Type: String
    Description: The alias for the database key stored in parameter store.

Resources:

# S3 Buckets

  TitlesBucket:
    Type: AWS::S3::Bucket

  TitlesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TitlesBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub '${TitlesBucket.Arn}/*'
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}'

  WebContentBucket:
    Type: AWS::S3::Bucket

  WebContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebContentBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub '${WebContentBucket.Arn}/*'
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}'

# DynamoDB Tables

  ContributorsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  BlackListedTokensTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: token_id
        Type: String

  TitlesTable:
    Type: AWS::DynamoDB::Table
    Properties:

      AttributeDefinitions:
      - AttributeName: contributor_id
        AttributeType: S
      - AttributeName: title_id
        AttributeType: S

      KeySchema:
      - AttributeName: contributor_id
        KeyType: HASH
      - AttributeName: title_id
        KeyType: RANGE

      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'

  GitHubReposTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: contributor_id
        Type: String

# SNS Topics

  SendEmailTopic:
    Type: AWS::SNS::Topic

# API Gateway

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        info:
          title: !Ref AWS::StackName

        securityDefinitions:
          authorizer:
            type: apiKey
            name: Authorization
            in: header
            x-amazon-apigateway-authtype: custom
            x-amazon-apigateway-authorizer:
              type: token
              authorizerUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Authorizer.Arn}/invocations'
              authorizerResultTtlInSeconds: 5

        paths:

          "/":
            get:
              x-amazon-apigateway-integration:
                contentHandling: "CONVERT_TO_TEXT"
                type: aws
                httpMethod: post
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebView.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Content-Type: "'text/html'"
                    responseTemplates:
                      text/html: "$input.path('$')"
              produces:
                - "text/html"
              responses:
                "200":
                  description: "200 response"
                  headers:
                    Content-Type:
                      type: "string"

          "/api/v1/contributors/register":
            post:
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiContributorRegistration.Arn}/invocations'
              responses: {}

          "/api/v1/contributors/verify":
            get:
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiContributorVerification.Arn}/invocations'
              responses: {}

          "/api/v1/titles":
            post:
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiTitlesCreate.Arn}/invocations'
              responses: {}
              security:
                - authorizer: []

          "/api/v1/titles/{title}/version":
            post:
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiTitlesUpdate.Arn}/invocations'
              responses: {}
              security:
                - authorizer: []

          "/jamf/v1/{contributor}/software":
            get:
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiJamfSoftware.Arn}/invocations'
              responses: {}

          "/jamf/v1/{contributor}/software/{titles}":
            get:
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiJamfSoftware.Arn}/invocations'
              responses: {}

          "/jamf/v1/{contributor}/patch/{title}":
            get:
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiJamfPatch.Arn}/invocations'
              responses: {}

# CloudFront Distribution

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub '${AWS::StackName}-origin-access-identity'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: Unified domain for CommunityPatch.

        Aliases:
          - !Ref DomainName

        ViewerCertificate:
          AcmCertificateArn: !Sub 'arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/${CertificateId}'
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.1_2016

        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 300
          ForwardedValues:
            Headers:
              - Accept
              - Referer
              - Authorization
              - Content-Type
            QueryString: true
          MaxTTL: 300
          TargetOriginId: ApiGatewayOrigin
          ViewerProtocolPolicy: https-only

        CacheBehaviors:
          - Compress: true
            DefaultTTL: 300
            ForwardedValues:
              QueryString: true
            PathPattern: '/titles/*'
            MaxTTL: 300
            TargetOriginId: TitlesBucketOrigin
            ViewerProtocolPolicy: allow-all

          - Compress: true
            DefaultTTL: 3600
            ForwardedValues:
              QueryString: true
            PathPattern: '/images/*'
            MaxTTL: 3600
            TargetOriginId: WebContentBucketOrigin
            ViewerProtocolPolicy: allow-all

        Origins:
          - DomainName: !Sub '${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com'
            Id: ApiGatewayOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
            OriginPath: /Prod

          - DomainName: !GetAtt TitlesBucket.DomainName
            Id: TitlesBucketOrigin
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'

          - DomainName: !GetAtt WebContentBucket.DomainName
            Id: WebContentBucketOrigin
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'

# Route 53 Record

  CloudFrontRoute53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref DomainName
      Type: A
      HostedZoneId: !Ref HostedZoneId
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        EvaluateTargetHealth: false
        HostedZoneId: Z2FDTNDATAQYW2

# Web View

  WebView:
    Type: AWS::Serverless::Function
    Description: Renders the main web page displaying all available titles.
    Properties:
      Runtime: python3.6
      Handler: web_view.lambda_handler
      CodeUri: ./src/functions/web_view
      Environment:
        Variables:
          CONTRIBUTORS_TABLE: !Ref ContributorsTable
          TITLES_TABLE: !Ref TitlesTable
      Policies:
        Statement:
          - Effect: Allow
            Action: dynamodb:Scan
            Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ContributorsTable}'
      Events:
        Index:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
                Ref: ApiGateway


# Contributor Management

  ApiContributorRegistration:
    Type: AWS::Serverless::Function
    Description: Creates and rotates tokens.
    Properties:
      Runtime: python3.6
      Handler: api_contributor_registration.lambda_handler
      CodeUri: ./src/functions/contributors/api_contributor_registration
      Environment:
        Variables:
          CONTRIBUTORS_TABLE: !Ref ContributorsTable
          DB_KEY_PARAMETER: !Ref DatabaseKeyParameter
          DOMAIN_NAME: !Ref DomainName
          EMAIL_SNS_TOPIC: !Ref SendEmailTopic
      Policies:
        Statement:
          - Effect: Allow
            Action: dynamodb:PutItem
            Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ContributorsTable}'
          - Effect: Allow
            Action: sns:Publish
            Resource: !Ref SendEmailTopic
          - Effect: Allow
            Action: ssm:GetParameter*
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/communitypatch*'
          - Effect: Allow
            Action: kms:Decrypt
            Resource: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${EncryptionKeyId}'
      Events:
        ApiContributorRegistration:
          Type: Api
          Properties:
            Path: /api/v1/contributors/register
            Method: post
            RestApiId:
                Ref: ApiGateway

  ApiContributorVerification:
    Type: AWS::Serverless::Function
    Description: Generate an API token upon account verification.
    Properties:
      Runtime: python3.6
      Handler: api_contributor_verification.lambda_handler
      CodeUri: ./src/functions/contributors/api_contributor_verification
      Environment:
        Variables:
          CONTRIBUTORS_TABLE: !Ref ContributorsTable
          DB_KEY_PARAMETER: !Ref DatabaseKeyParameter
          DOMAIN_NAME: !Ref DomainName
          EMAIL_SNS_TOPIC: !Ref SendEmailTopic
          SECRET_KEY: !Ref ApiTokenSecretKey
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:UpdateItem
            Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ContributorsTable}'
          - Effect: Allow
            Action: sns:Publish
            Resource: !Ref SendEmailTopic
          - Effect: Allow
            Action: ssm:GetParameter*
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/communitypatch*'
          - Effect: Allow
            Action: kms:Decrypt
            Resource: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${EncryptionKeyId}'
      Events:
        ApiContributorRegistration:
          Type: Api
          Properties:
            Path: /api/v1/contributors/verify
            Method: get
            RestApiId:
                Ref: ApiGateway

# Token Authorizer

  Authorizer:
    Type: AWS::Serverless::Function
    Description: Token validation for Uploader.
    Properties:
      Runtime: python3.6
      Handler: authorizer.lambda_handler
      CodeUri: ./src/functions/authorizer
      Environment:
        Variables:
          BLACKLIST_TABLE: !Ref BlackListedTokensTable
          SECRET_KEY: !Ref ApiTokenSecretKey
      Policies:
        Statement:
          - Effect: Allow
            Action: dynamodb:GetItem
            Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${BlackListedTokensTable}'

  AuthorizerPermissions:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ApiGateway
      - Authorizer
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: Authorizer
      Principal: apigateway.amazonaws.com

# Titles API

  ApiTitlesCreate:
    Type: AWS::Serverless::Function
    Description: Handles API requests for creating software title definitions.
    Properties:
      Runtime: python3.6
      Handler: api_titles_create.lambda_handler
      CodeUri: ./src/functions/titles/api_titles_create
      Environment:
        Variables:
          TITLES_BUCKET: !Ref TitlesBucket
          TITLES_TABLE: !Ref TitlesTable
      Policies:
        Statement:
          - Effect: Allow
            Action: s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${TitlesBucket}/*'
          - Effect: Allow
            Action: dynamodb:PutItem
            Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TitlesTable}'
      Events:
        CreateTitle:
          Type: Api
          Properties:
            Path: /api/v1/titles
            Method: post
            RestApiId:
                Ref: ApiGateway

  ApiTitlesUpdate:
    Type: AWS::Serverless::Function
    Description: Handles API requests for updating patch definitions.
    Properties:
      Runtime: python3.6
      Handler: api_titles_update.lambda_handler
      CodeUri: ./src/functions/titles/api_titles_update
      Environment:
        Variables:
          TITLES_BUCKET: !Ref TitlesBucket
          TITLES_TABLE: !Ref TitlesTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
             - s3:GetObject
             - s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${TitlesBucket}/*'
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:UpdateItem
            Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TitlesTable}'
      Events:
        UpdateTitle:
          Type: Api
          Properties:
            Path: /api/v1/titles/{title}/version
            Method: post
            RestApiId:
                Ref: ApiGateway

# Jamf API

  ApiJamfSoftware:
    Type: AWS::Serverless::Function
    Description: Handles Jamf Pro requests for software lists.
    Properties:
      Runtime: python3.6
      Handler: api_jamf_software.lambda_handler
      CodeUri: ./src/functions/jamf/api_jamf_software
      Environment:
        Variables:
          TITLES_TABLE: !Ref TitlesTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
             - dynamodb:GetItem
             - dynamodb:Query
            Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TitlesTable}'
      Events:
        GetAllSoftware:
          Type: Api
          Properties:
            Path: /jamf/v1/{contributor}/software
            Method: get
            RestApiId:
                Ref: ApiGateway
        GetSelectSoftware:
          Type: Api
          Properties:
            Path: /jamf/v1/{contributor}/software/{titles}
            Method: get
            RestApiId:
                Ref: ApiGateway

  ApiJamfPatch:
    Type: AWS::Serverless::Function
    Description: Handles Jamf Pro requests for patch definitions.
    Properties:
      Runtime: python3.6
      Handler: api_jamf_patch.lambda_handler
      CodeUri: ./src/functions/jamf/api_jamf_patch
      Environment:
        Variables:
          DOMAIN_NAME: !Ref DomainName
          TITLES_BUCKET: !Ref TitlesBucket
      Policies:
        Statement:
          - Effect: Allow
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${TitlesBucket}/*'
      Events:
        GetPatch:
          Type: Api
          Properties:
            Path: /jamf/v1/{contributor}/patch/{title}
            Method: get
            RestApiId:
                Ref: ApiGateway

# Email Service

  EmailService:
    Type: AWS::Serverless::Function
    Description:
    Properties:
      Runtime: python3.6
      Handler: email_service.lambda_handler
      CodeUri: ./src/functions/email_service
      Environment:
        Variables:
          SENDER_ADDRESS: !Ref EmailSenderAddress
      Policies:
        Statement:
          - Effect: Allow
            Action: ses:SendEmail
            Resource: '*'
            Condition:
              StringEquals:
                ses:FromAddress: !Ref EmailSenderAddress
      Events:
        SnsTopic:
          Type: SNS
          Properties:
            Topic: !Ref SendEmailTopic