AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A serverless Patch Server for Jamf Pro using AWS.

Resources:
  PatchServerFunc:
    Type: AWS::Serverless::Function
    Properties:
      Handler: patch_server.lambda_handler
      Runtime: python3.6
      CodeUri: ./PatchServerFunc
      Environment:
        Variables:
          S3_BUCKET: !Ref Bucket
      Policies:
        Statement:
          - Effect: Allow
            Action: s3:ListBucket
            Resource: !Sub 'arn:aws:s3:::${Bucket}'
          - Effect: Allow
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${Bucket}/*'
      Events:
        Software:
          Type: Api
          Properties:
            Path: /software
            Method: get
        SoftwareTitles:
          Type: Api
          Properties:
            Path: /software/{proxy+}
            Method: get
        PatchTitle:
          Type: Api
          Properties:
            Path: /patch/{proxy+}
            Method: get

  SubscribeFunc:
    Type: AWS::Serverless::Function
    Properties:
      Handler: subscribe.lambda_handler
      Runtime: python3.6
      CodeUri: ./SubscribeFunc
      Environment:
        Variables:
          S3_BUCKET: !Ref Bucket
          TABLE_NAME: !Ref DynamoDBTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTable}'
          - Effect: Allow
            Action: s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${Bucket}/*'
      Events:
        NewSubscription:
          Type: Api
          Properties:
            Path: /subscribe
            Method: post

  Bucket:
    Type: AWS::S3::Bucket

  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
