AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: A serverless Patch Server for Jamf Pro using AWS.

Resources:

# DynamoDB Tables

  ContributorsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: contributor_id
        Type: String

  TitlesTable:
    Type: AWS::DynamoDB::Table
    Properties:

      AttributeDefinitions:
      - AttributeName: contributor_id
        AttributeType: S
      - AttributeName: title_id
        AttributeType: S

      KeySchema:
      - AttributeName: contributor_id
        KeyType: HASH
      - AttributeName: title_id
        KeyType: RANGE
#
#      LocalSecondaryIndexes:
#      - IndexName: ContributorTitlesIndex
#        KeySchema:
#        - AttributeName: contributor_id
#          KeyType: HASH
#        - AttributeName: title_id
#          KeyType: RANGE
#        Projection:
#          ProjectionType: KEYS_ONLY

      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'

  GitHubReposTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: contributor_id
        Type: String
